[package]
name = "covalent-cli"
description = "Covalent operator and developer CLI"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "covalent"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
covalent-core = { path = "../covalent-core" }
covalent-protocol = { path = "../covalent-protocol" }
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true
