use base64::Engine as _;
use base64::engine::general_purpose::URL_SAFE_NO_PAD;
use covalent_protocol::{
    FOLDER_SHARE_SCHEMA_VERSION, FolderShareAcceptance, FolderShareCommit, FolderShareOffer,
    SyncEngineBinding, SyncEngineBindingError, SyncEngineDeviceId,
};
use uuid::Uuid;

use crate::{
    DeviceIdentity, FolderSharingError, MAX_FOLDER_SHARE_LIFETIME_MS, accept_folder_share_offer,
    commit_folder_share, create_folder_share_offer, folder_share_acceptance_digest,
    folder_share_offer_digest, verify_folder_share_acceptance, verify_folder_share_commit,
    verify_folder_share_offer, verify_fresh_folder_share_acceptance,
    verify_fresh_folder_share_offer,
};

const SOURCE_ENGINE_ID: &str = "EA2I6UL-UUWKJDX-NGOC6QS-U2IZR4Z-LXY5CB7-3KBVQRG-4CNFBV7-RACTXQF";
const TARGET_ENGINE_ID: &str = "FZ23CS4-PDV743V-32LS44M-TCIUBAQ-RQ3OC4X-XN6EG66-BGUCZH4-OISTMAE";
const NOW: u64 = 1_800_000_000_000;

#[test]
fn frozen_checkpoint46_v1_records_keep_their_original_valid_signatures() {
    // Generated by unmodified checkpoint-46 signing code in a separate source
    // export and target directory. This fixture contains only public records.
    #[derive(serde::Deserialize)]
    struct LegacyRecords {
        source: crate::PublicIdentity,
        target: crate::PublicIdentity,
        offer: FolderShareOffer,
        acceptance: FolderShareAcceptance,
        commit: FolderShareCommit,
    }
    let records: LegacyRecords = serde_json::from_str(include_str!(
        "../tests/fixtures/folder-share-v1-checkpoint46.json"
    ))
    .unwrap();
    assert_eq!(records.offer.schema_version, 1);
    assert!(records.offer.link_policy.is_none());
    assert!(
        !serde_json::to_string(&records.offer)
            .unwrap()
            .contains("linkPolicy")
    );
    verify_folder_share_offer(&records.offer, &records.source, records.target.device_id).unwrap();
    verify_folder_share_acceptance(
        &records.offer,
        &records.acceptance,
        &records.source,
        &records.target,
    )
    .unwrap();
    verify_folder_share_commit(
        &records.offer,
        &records.acceptance,
        &records.commit,
        &records.source,
        &records.target,
    )
    .unwrap();
}

struct Records {
    source: DeviceIdentity,
    target: DeviceIdentity,
    offer: FolderShareOffer,
    acceptance: FolderShareAcceptance,
    commit: FolderShareCommit,
}

fn binding(owner: covalent_protocol::DeviceId, id: &str, address: &str) -> SyncEngineBinding {
    SyncEngineBinding::new(owner, id, address).expect("valid engine binding")
}

fn tamper_first(value: &mut String) {
    let replacement = if value.starts_with('A') { "B" } else { "A" };
    value.replace_range(0..1, replacement);
}

fn records(pairing_id: Option<&str>) -> Records {
    let source = DeviceIdentity::generate();
    let target = DeviceIdentity::generate();
    let offer = create_folder_share_offer(
        &source,
        target.device_id(),
        Uuid::from_u128(0x1234_5678_1234_5678_1234_5678_1234_5678),
        "Shared photos",
        binding(source.device_id(), SOURCE_ENGINE_ID, "203.0.113.10:22000"),
        pairing_id,
        NOW,
        60_000,
    )
    .expect("offer");
    let acceptance = accept_folder_share_offer(
        &offer,
        &source.public_identity(),
        &target,
        binding(target.device_id(), TARGET_ENGINE_ID, "[2001:db8::25]:22000"),
        NOW + 1,
    )
    .expect("acceptance");
    let commit = commit_folder_share(
        &offer,
        &acceptance,
        &source,
        &target.public_identity(),
        NOW + 2,
    )
    .expect("commit");
    Records {
        source,
        target,
        offer,
        acceptance,
        commit,
    }
}

#[test]
fn one_way_policy_is_signed_and_cannot_be_removed_or_changed() {
    let legacy = records(None);
    assert!(
        !serde_json::to_string(&legacy.offer)
            .unwrap()
            .contains("linkPolicy")
    );
    let policy = covalent_protocol::FolderLinkPolicy::default();
    let offer = crate::create_folder_share_offer_with_policy(
        &legacy.source,
        legacy.target.device_id(),
        legacy.offer.folder_id,
        "Photos",
        legacy.offer.source_engine.clone(),
        None,
        NOW,
        60_000,
        Some(policy),
    )
    .unwrap();
    assert_eq!(
        offer.schema_version,
        covalent_protocol::FOLDER_LINK_SCHEMA_VERSION
    );
    verify_folder_share_offer(
        &offer,
        &legacy.source.public_identity(),
        legacy.target.device_id(),
    )
    .unwrap();
    for changed in [
        None,
        Some(covalent_protocol::FolderLinkPolicy {
            propagate_source_deletions: true,
            ..policy
        }),
        Some(covalent_protocol::FolderLinkPolicy {
            restore_local_deletions: true,
            ..policy
        }),
    ] {
        let mut tampered = offer.clone();
        tampered.link_policy = changed;
        assert!(
            verify_folder_share_offer(
                &tampered,
                &legacy.source.public_identity(),
                legacy.target.device_id()
            )
            .is_err()
        );
    }
    let acceptance = accept_folder_share_offer(
        &offer,
        &legacy.source.public_identity(),
        &legacy.target,
        binding(
            legacy.target.device_id(),
            TARGET_ENGINE_ID,
            "[2001:db8::25]:22000",
        ),
        NOW + 1,
    )
    .unwrap();
    assert_eq!(acceptance.schema_version, offer.schema_version);
    let commit = commit_folder_share(
        &offer,
        &acceptance,
        &legacy.source,
        &legacy.target.public_identity(),
        NOW + 2,
    )
    .unwrap();
    assert_eq!(commit.schema_version, offer.schema_version);
    verify_folder_share_commit(
        &offer,
        &acceptance,
        &commit,
        &legacy.source.public_identity(),
        &legacy.target.public_identity(),
    )
    .unwrap();
}

#[test]
fn real_identities_round_trip_complete_signed_chain() {
    let records = records(Some("EjRWeBI0VngSNFZ4EjRWeA"));
    verify_fresh_folder_share_offer(
        &records.offer,
        &records.source.public_identity(),
        records.target.device_id(),
        NOW,
    )
    .expect("fresh offer");
    verify_fresh_folder_share_acceptance(
        &records.offer,
        &records.acceptance,
        &records.source.public_identity(),
        &records.target.public_identity(),
        NOW + 2,
    )
    .expect("fresh acceptance");
    verify_folder_share_commit(
        &records.offer,
        &records.acceptance,
        &records.commit,
        &records.source.public_identity(),
        &records.target.public_identity(),
    )
    .expect("durable commit");
    assert_eq!(
        records.commit.offer_digest,
        folder_share_offer_digest(&records.offer).expect("offer digest")
    );
    assert_eq!(
        records.commit.acceptance_digest,
        folder_share_acceptance_digest(&records.offer, &records.acceptance)
            .expect("acceptance digest")
    );
}

#[test]
fn expiry_applies_only_to_fresh_intake() {
    let records = records(None);
    let expiry = records.offer.expires_at_unix_ms;
    verify_fresh_folder_share_offer(
        &records.offer,
        &records.source.public_identity(),
        records.target.device_id(),
        expiry - 1,
    )
    .expect("last live millisecond");
    assert_eq!(
        verify_fresh_folder_share_offer(
            &records.offer,
            &records.source.public_identity(),
            records.target.device_id(),
            expiry,
        ),
        Err(FolderSharingError::NotFresh)
    );
    verify_folder_share_offer(
        &records.offer,
        &records.source.public_identity(),
        records.target.device_id(),
    )
    .expect("durable offer replay after expiry");
    verify_folder_share_commit(
        &records.offer,
        &records.acceptance,
        &records.commit,
        &records.source.public_identity(),
        &records.target.public_identity(),
    )
    .expect("durable committed share replay after expiry");
}

#[test]
fn future_clock_skew_has_an_exact_boundary() {
    let records = records(None);
    verify_fresh_folder_share_offer(
        &records.offer,
        &records.source.public_identity(),
        records.target.device_id(),
        NOW - 5 * 60 * 1_000,
    )
    .expect("skew boundary");
    assert_eq!(
        verify_fresh_folder_share_offer(
            &records.offer,
            &records.source.public_identity(),
            records.target.device_id(),
            NOW - 5 * 60 * 1_000 - 1,
        ),
        Err(FolderSharingError::NotFresh)
    );
    assert_eq!(
        verify_fresh_folder_share_acceptance(
            &records.offer,
            &records.acceptance,
            &records.source.public_identity(),
            &records.target.public_identity(),
            NOW - 5 * 60 * 1_000,
        ),
        Err(FolderSharingError::NotFresh)
    );
    verify_fresh_folder_share_acceptance(
        &records.offer,
        &records.acceptance,
        &records.source.public_identity(),
        &records.target.public_identity(),
        NOW - 5 * 60 * 1_000 + 1,
    )
    .expect("acceptance skew boundary");
}

#[test]
fn constructor_rejects_invalid_bounds_before_signing() {
    let source = DeviceIdentity::generate();
    let target = DeviceIdentity::generate();
    let source_binding = || binding(source.device_id(), SOURCE_ENGINE_ID, "198.51.100.4:22000");
    for (label, lifetime) in [
        ("", 1),
        ("\n", 1),
        (&"a".repeat(257), 1),
        ("folder", 0),
        ("folder", MAX_FOLDER_SHARE_LIFETIME_MS + 1),
    ] {
        assert!(
            create_folder_share_offer(
                &source,
                target.device_id(),
                Uuid::new_v4(),
                label,
                source_binding(),
                None,
                NOW,
                lifetime,
            )
            .is_err()
        );
    }
    assert!(
        create_folder_share_offer(
            &source,
            source.device_id(),
            Uuid::new_v4(),
            "folder",
            source_binding(),
            None,
            NOW,
            1,
        )
        .is_err()
    );
    assert!(
        create_folder_share_offer(
            &source,
            target.device_id(),
            Uuid::nil(),
            "folder",
            source_binding(),
            None,
            NOW,
            1,
        )
        .is_err()
    );
    assert!(
        create_folder_share_offer(
            &source,
            covalent_protocol::DeviceId::from_uuid(Uuid::nil()),
            Uuid::new_v4(),
            "folder",
            source_binding(),
            None,
            NOW,
            1,
        )
        .is_err()
    );
    let exact = create_folder_share_offer(
        &source,
        target.device_id(),
        Uuid::new_v4(),
        &"a".repeat(256),
        source_binding(),
        Some("AAECAwQFBgcICQoLDA0ODw"),
        NOW,
        MAX_FOLDER_SHARE_LIFETIME_MS,
    )
    .expect("exact bounds");
    assert_eq!(exact.expires_at_unix_ms, NOW + MAX_FOLDER_SHARE_LIFETIME_MS);
    assert_eq!(exact.offer_id.get_version_num(), 4);
}

#[test]
fn canonical_engine_ids_and_endpoints_are_strict() {
    assert!(SyncEngineDeviceId::parse(SOURCE_ENGINE_ID).is_ok());
    for id in [
        SOURCE_ENGINE_ID.to_ascii_lowercase(),
        SOURCE_ENGINE_ID.replace('-', " "),
        SOURCE_ENGINE_ID.replacen('E', "F", 1),
    ] {
        assert_eq!(
            SyncEngineDeviceId::parse(&id),
            Err(SyncEngineBindingError::InvalidDeviceId)
        );
    }
    let owner = DeviceIdentity::generate().device_id();
    for endpoint in [
        "0.0.0.0:22000",
        "255.255.255.255:22000",
        "224.0.0.1:22000",
        "127.0.0.1:0",
        "[::]:22000",
        "[ff02::1]:22000",
        "[fe80::1]:22000",
        "[fe80::1%3]:22000",
        "[2001:db8::1%3]:22000",
        "[2001:0db8::1]:22000",
        "example.com:22000",
    ] {
        assert!(
            SyncEngineBinding::new(owner, SOURCE_ENGINE_ID, endpoint).is_err(),
            "accepted {endpoint}"
        );
    }
    for endpoint in [
        "127.0.0.1:22000",
        "10.0.0.2:22000",
        "198.51.100.9:22000",
        "8.8.8.8:22000",
        "[2001:db8::1]:22000",
    ] {
        SyncEngineBinding::new(owner, SOURCE_ENGINE_ID, endpoint)
            .unwrap_or_else(|_| panic!("rejected {endpoint}"));
    }
}

#[test]
fn engine_binding_owner_is_cryptographically_bound() {
    let mut first = records(None);
    first.offer.source_engine.covalent_device_id = first.target.device_id();
    assert_eq!(
        verify_folder_share_offer(
            &first.offer,
            &first.source.public_identity(),
            first.target.device_id(),
        ),
        Err(FolderSharingError::InvalidEngineBinding)
    );
    let mut second = records(None);
    second.acceptance.target_engine.covalent_device_id = second.source.device_id();
    assert_eq!(
        verify_folder_share_acceptance(
            &second.offer,
            &second.acceptance,
            &second.source.public_identity(),
            &second.target.public_identity(),
        ),
        Err(FolderSharingError::InvalidEngineBinding)
    );
}

#[test]
fn wrong_trusted_peer_and_counterpart_are_rejected() {
    let records = records(None);
    let stranger = DeviceIdentity::generate();
    assert_eq!(
        verify_folder_share_offer(
            &records.offer,
            &stranger.public_identity(),
            records.target.device_id(),
        ),
        Err(FolderSharingError::InvalidSignature)
    );
    assert_eq!(
        verify_folder_share_offer(
            &records.offer,
            &records.source.public_identity(),
            stranger.device_id(),
        ),
        Err(FolderSharingError::WrongPeer)
    );
    assert_eq!(
        verify_folder_share_acceptance(
            &records.offer,
            &records.acceptance,
            &records.source.public_identity(),
            &stranger.public_identity(),
        ),
        Err(FolderSharingError::InvalidSignature)
    );
}

#[test]
fn offer_tampering_never_verifies() {
    let records = records(None);
    let mut variants = Vec::new();
    let mut changed = records.offer.clone();
    changed.label.push('!');
    variants.push(changed);
    let mut changed = records.offer.clone();
    changed.folder_id = Uuid::new_v4();
    variants.push(changed);
    let mut changed = records.offer.clone();
    changed.source_engine.direct_address = "203.0.113.11:22000".to_owned();
    variants.push(changed);
    let mut changed = records.offer.clone();
    changed.nonce = URL_SAFE_NO_PAD.encode([7_u8; 24]);
    variants.push(changed);
    let mut changed = records.offer.clone();
    tamper_first(&mut changed.signature);
    variants.push(changed);
    for changed in variants {
        assert!(
            verify_folder_share_offer(
                &changed,
                &records.source.public_identity(),
                records.target.device_id(),
            )
            .is_err()
        );
    }
}

#[test]
fn noncanonical_base64_and_pairing_ids_are_rejected() {
    let records = records(None);
    let mut offer = records.offer.clone();
    offer.nonce.push('=');
    assert_eq!(
        verify_folder_share_offer(
            &offer,
            &records.source.public_identity(),
            records.target.device_id(),
        ),
        Err(FolderSharingError::InvalidRecord)
    );
    let source = DeviceIdentity::generate();
    let target = DeviceIdentity::generate();
    for invalid in ["", "not+base64", "AAAAAAAAAAAAAAAAAAAAAA=="] {
        assert!(
            create_folder_share_offer(
                &source,
                target.device_id(),
                Uuid::new_v4(),
                "folder",
                binding(source.device_id(), SOURCE_ENGINE_ID, "127.0.0.1:22000"),
                Some(invalid),
                NOW,
                1,
            )
            .is_err()
        );
    }
}

#[test]
fn acceptance_digest_signature_and_time_substitution_fail() {
    let records = records(None);
    let mut variants = Vec::new();
    let mut changed = records.acceptance.clone();
    changed.offer_digest = "0".repeat(64);
    variants.push(changed);
    let mut changed = records.acceptance.clone();
    changed.accepted_at_unix_ms += 1;
    variants.push(changed);
    let mut changed = records.acceptance.clone();
    tamper_first(&mut changed.signature);
    variants.push(changed);
    for changed in variants {
        assert!(
            verify_folder_share_acceptance(
                &records.offer,
                &changed,
                &records.source.public_identity(),
                &records.target.public_identity(),
            )
            .is_err()
        );
    }
    let mut too_late = records.acceptance.clone();
    too_late.accepted_at_unix_ms = records.offer.expires_at_unix_ms;
    assert_eq!(
        verify_folder_share_acceptance(
            &records.offer,
            &too_late,
            &records.source.public_identity(),
            &records.target.public_identity(),
        ),
        Err(FolderSharingError::InvalidRecord)
    );
}

#[test]
fn commit_digest_source_and_signature_substitution_fail() {
    let records = records(None);
    let mut changed = records.commit.clone();
    changed.acceptance_digest = "0".repeat(64);
    assert!(
        verify_folder_share_commit(
            &records.offer,
            &records.acceptance,
            &changed,
            &records.source.public_identity(),
            &records.target.public_identity(),
        )
        .is_err()
    );
    let mut changed = records.commit.clone();
    changed.source_device_id = records.target.device_id();
    assert!(
        verify_folder_share_commit(
            &records.offer,
            &records.acceptance,
            &changed,
            &records.source.public_identity(),
            &records.target.public_identity(),
        )
        .is_err()
    );
    let mut changed = records.commit.clone();
    tamper_first(&mut changed.signature);
    assert_eq!(
        verify_folder_share_commit(
            &records.offer,
            &records.acceptance,
            &changed,
            &records.source.public_identity(),
            &records.target.public_identity(),
        ),
        Err(FolderSharingError::InvalidSignature)
    );
}

#[test]
fn strict_json_rejects_unknown_fields_and_invalid_engine_id() {
    let records = records(None);
    let mut value = serde_json::to_value(&records.offer).expect("offer JSON");
    value
        .as_object_mut()
        .expect("object")
        .insert("unexpected".to_owned(), serde_json::json!(true));
    assert!(serde_json::from_value::<FolderShareOffer>(value).is_err());

    let mut value = serde_json::to_value(&records.offer).expect("offer JSON");
    value["sourceEngine"]["engineDeviceId"] = serde_json::json!(SOURCE_ENGINE_ID.to_lowercase());
    assert!(serde_json::from_value::<FolderShareOffer>(value).is_err());
}

#[test]
fn errors_and_debug_never_include_record_contents() {
    let records = records(None);
    let error = verify_folder_share_offer(
        &records.offer,
        &records.source.public_identity(),
        DeviceIdentity::generate().device_id(),
    )
    .expect_err("wrong peer");
    let rendered = format!("{error:?} {error}");
    assert!(!rendered.contains(&records.offer.label));
    assert!(!rendered.contains(&records.offer.nonce));
    assert_eq!(records.offer.schema_version, FOLDER_SHARE_SCHEMA_VERSION);
}
