use std::fs::{self, File};
use std::io::{Cursor, Write as _};
use std::path::Path;
use std::str::FromStr as _;

use base64::Engine as _;
use covalent_core::{BackupOptions, Engine, EngineOptions, JobControl, RestoreOptions};
use covalent_protocol::BackupId;
use tempfile::tempdir;
use zip::ZipArchive;

const PRIOR_COMMIT: &str = "9ac1f7e3a9e00d5bec6013a78ffc38590a46af12";
const PRIOR_STATE_ZIP: &str = include_str!("fixtures/prior-package-9ac1f7e-state.zip.b64");

#[test]
fn frozen_prior_package_state_upgrades_restores_and_accepts_a_new_snapshot() {
    let state = tempdir().expect("state directory");
    extract_frozen_state(state.path());
    let backup_id = BackupId::from_str("11111111-2222-4333-8444-555555555555").expect("backup ID");

    let engine = Engine::open(EngineOptions::new(state.path())).unwrap_or_else(|error| {
        panic!("current engine could not open state generated by {PRIOR_COMMIT}: {error}")
    });
    let backups = engine.list_backups().expect("list prior backups");
    assert_eq!(backups.len(), 1);
    assert_eq!(backups[0].backup_id, backup_id);
    assert_eq!(backups[0].latest_snapshot_id.as_deref(), Some("0001"));
    assert_eq!(backups[0].snapshot_count, 1);
    assert!(
        engine
            .verify_snapshot(backup_id, "0001")
            .expect("verify prior snapshot")
            .is_intact(),
        "prior encrypted chunks must remain authenticated"
    );

    let restore = tempdir().expect("restore directory");
    let plan = engine
        .preview_restore(
            backup_id,
            "0001",
            restore.path(),
            &RestoreOptions::all("prior-package-restore"),
        )
        .expect("preview prior snapshot");
    let report = engine
        .restore(&plan, &JobControl::new())
        .expect("restore prior snapshot");
    assert!(report.files_restored > 0);
    assert_eq!(tree_file_count(restore.path()), report.files_restored);

    let source = tempdir().expect("new source directory");
    fs::create_dir(source.path().join("nested")).expect("new source child");
    let mut current = File::create(source.path().join("nested/current.txt")).expect("new file");
    current
        .write_all(b"snapshot created after package upgrade\n")
        .expect("write new file");
    current.sync_all().expect("sync new file");
    let mut options = BackupOptions::new(backup_id, "0002", "post-upgrade-backup");
    options.display_name = "Frozen prior package fixture".to_owned();
    options.created_at_unix_ms = 2;
    engine
        .backup(source.path(), &options, &JobControl::new(), |_| {})
        .expect("commit a current-format snapshot after upgrade");
    assert!(
        engine
            .verify_snapshot(backup_id, "0002")
            .expect("verify current snapshot")
            .is_intact()
    );
    drop(engine);

    let reopened = Engine::open(EngineOptions::new(state.path())).expect("reopen upgraded state");
    let backups = reopened.list_backups().expect("list upgraded backups");
    assert_eq!(backups.len(), 1);
    assert_eq!(backups[0].latest_snapshot_id.as_deref(), Some("0002"));
    assert_eq!(backups[0].snapshot_count, 2);
    assert!(
        reopened
            .verify_snapshot(backup_id, "0001")
            .expect("reverify frozen snapshot")
            .is_intact()
    );
    assert!(
        reopened
            .verify_snapshot(backup_id, "0002")
            .expect("reverify new snapshot")
            .is_intact()
    );
}

fn extract_frozen_state(destination: &Path) {
    let encoded = PRIOR_STATE_ZIP.trim();
    let bytes = base64::engine::general_purpose::STANDARD
        .decode(encoded)
        .expect("decode frozen state fixture");
    let mut archive = ZipArchive::new(Cursor::new(bytes)).expect("open frozen state fixture");
    for index in 0..archive.len() {
        let mut entry = archive.by_index(index).expect("frozen state entry");
        let relative = entry
            .enclosed_name()
            .unwrap_or_else(|| panic!("unsafe fixture entry {}", entry.name()))
            .to_path_buf();
        assert!(!relative.as_os_str().is_empty());
        #[cfg(unix)]
        if let Some(mode) = entry.unix_mode() {
            assert_ne!(
                mode & 0o170_000,
                0o120_000,
                "fixture must not contain links"
            );
        }
        let output = destination.join(relative);
        if entry.is_dir() {
            fs::create_dir_all(&output).expect("create frozen state directory");
            set_private_mode(&output, 0o700);
            continue;
        }
        let parent = output.parent().expect("fixture parent");
        fs::create_dir_all(parent).expect("create frozen state parent");
        set_private_mode(parent, 0o700);
        let mut file = File::create(&output).expect("create frozen state file");
        std::io::copy(&mut entry, &mut file).expect("extract frozen state file");
        file.sync_all().expect("sync frozen state file");
        set_private_mode(&output, 0o600);
    }
}

fn tree_file_count(root: &Path) -> usize {
    walkdir::WalkDir::new(root)
        .follow_links(false)
        .into_iter()
        .map(|entry| entry.expect("walk restored fixture"))
        .filter(|entry| entry.file_type().is_file())
        .count()
}

#[cfg(unix)]
fn set_private_mode(path: &Path, mode: u32) {
    use std::os::unix::fs::PermissionsExt as _;

    fs::set_permissions(path, fs::Permissions::from_mode(mode)).expect("set private fixture mode");
}

#[cfg(not(unix))]
fn set_private_mode(_path: &Path, _mode: u32) {}
