#!/usr/bin/env python3
"""Trust one Tailscale user on the private Serve socket; keep tokens server-side."""
import argparse
import json
import os
from pathlib import Path
import re
import stat
import tempfile
from urllib.parse import urlsplit


def access_rule(origin, login, token):
    url = urlsplit(origin)
    if (url.scheme != "https" or not url.hostname or url.username or url.password
            or url.path or url.query or url.fragment
            or not re.fullmatch(r"[a-z0-9.-]+(?::[0-9]{1,5})?", url.netloc)
            or (url.port is not None and not 1 <= url.port <= 65535)):
        raise ValueError("origin must be an exact HTTPS hostname and optional port")
    if not re.fullmatch(r"[A-Za-z0-9_.+@-]+", login):
        raise ValueError("use the exact Tailscale login email, without wildcards")
    if not re.fullmatch(r"[A-Za-z0-9_-]{32,512}", token):
        raise ValueError("expected the claimed local API token")
    quote = json.dumps
    return f'''# Generated by configure-trusted-console.py. Contains a secret; mode 0600.
@trusted_console {{
    path /api/v1/*
    header Tailscale-User-Login {quote(login)}
    header X-Covalent-Console "1"
    header Sec-Fetch-Site "same-origin"
    # Serve rewrites Host to localhost when forwarding to a Unix socket.
    expression `({{http.request.hostport}} == "localhost" || {{http.request.hostport}} == {quote(url.netloc)}) && ({{http.request.header.Origin}} == "" || {{http.request.header.Origin}} == {quote(origin)})`
}}
handle @trusted_console {{
    reverse_proxy 127.0.0.1:8787 {{
        header_up Authorization "Bearer {token}"
    }}
}}
'''


def configure(config_dir, token_file, origin, login):
    metadata = token_file.lstat()
    if not stat.S_ISREG(metadata.st_mode) or metadata.st_mode & 0o077:
        raise ValueError("token file must be an owner-only regular file")
    rule = access_rule(origin, login, token_file.read_text().strip())
    directory = config_dir / "console-access"
    directory.mkdir(mode=0o700, exist_ok=True)
    if directory.is_symlink() or directory.stat().st_mode & 0o077:
        raise ValueError("console-access must be an owner-only directory")
    fd, temporary = tempfile.mkstemp(prefix=".access-", dir=directory)
    try:
        with os.fdopen(fd, "w") as stream:
            stream.write(rule)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, directory / "tailscale.caddy")
    finally:
        Path(temporary).unlink(missing_ok=True)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config-dir", type=Path, required=True)
    parser.add_argument("--token-file", type=Path, required=True)
    parser.add_argument("--origin", required=True)
    parser.add_argument("--tailscale-user", required=True)
    args = parser.parse_args()
    try:
        configure(args.config_dir, args.token_file, args.origin, args.tailscale_user)
    except (OSError, ValueError) as error:
        parser.exit(1, f"Cannot configure trusted console: {error}\n")
    print("Trusted console configured. Keep console-access owned by the container UID and restart Covalent.")
